### ISSUE TITLE
jTweetsAnywhere

### ISSUE THREAD

**Issue by tbillenstein** [lancejpollard/cached-commons#11]
jTweetsAnywhere is a jQuery Twitter Widget with @Anywhere support that simplifies the integration of Twitter services into any website.

[Home] http://thomasbillenstein.com/jTweetsAnywhere/
[Demo] http://thomasbillenstein.com/jTweetsAnywhere/demo/

Would be great if you could add it.
Thanks

**Comment by lancejpollard** [comment]
Added!

**Comment by tbillenstein** [comment]
Thanks for adding
