### ISSUE TITLE
[Feature Request] Add scriptsrc.net style copy to clipboard feature

### ISSUE THREAD

**Issue by rajeshg** [lancejpollard/cached-commons#3]
Hi,

It would be great if you can add scriptsrc.net style copy to clipboard feature to cached-commons. This would make the service very usable.
For example, if I need jQuery in my project - I will just click 'copy to clipboard' - which adds "<script src='xxxxxxx/jquery.min.js" type='text/javascript"></script" to my clipboard. 

Thanks,
Rajesh.

**Comment by lancejpollard** [comment]
will do!  looks great.  right now on http://cachedcommons.org, you can click the rows and a tab on the right will appear, click that and you can copy script tags just the same.  I'll make that easier like scriptsrc.net.

Cheers

**Comment by rajeshg** [comment]
You are right. Didn't realize that before. 

Keep the good work going.
