### ISSUE TITLE
dropdownReplacement plugin

### ISSUE THREAD

**Issue by mkoryak** [lancejpollard/cached-commons#4]
can you add dropdownReplacement plugin, its a plugin for converting an existing select box into a javascript widget that is fully skinnable, but has all (and more) functionality of the native dropdown.

here is a site with demos/api 

http://programmingdrunk.com/current-projects/dropdownReplacement/#getting-started

**Comment by lancejpollard** [comment]
Added, thanks for the link!

http://cachedcommons.org/cache/jquery-dropdown-replacement/0.5.0/javascripts/jquery-dropdown-replacement.js
