### ISSUE TITLE
Update Modernizer

### ISSUE THREAD

**Issue by Mnkras** [lancejpollard/cached-commons#51]
Can you update modernizr to 1.7 (you have 1.5)

Thanks

**Comment by solenoid** [comment]
I'd also like to see the bump to 1.7 so the latest release is available.

Thanks in advance.

**Comment by marceltt** [comment]
And now there is [Modernizr 2](http://www.modernizr.com/news/modernizr-2). The [development file](http://www.modernizr.com/downloads/modernizr-2.0.3.js) would be nice to have hosted here.
