### ISSUE TITLE
Colorbox please

### ISSUE THREAD

**Issue by lardissone** [lancejpollard/cached-commons#7]
http://colorpowered.com/colorbox/

It's a great Tightbox alternative, and works great.

thanks, cc is great!

**Comment by lancejpollard** [comment]
Added!

http://cachedcommons.org/cache/jquery-colorbox/1.3.9/javascripts/jquery-colorbox.js

**Comment by lardissone** [comment]
Awesome, thank you!

Another popular ones are jCarousel and jCarousel Lite:
http://sorgalla.com/projects/jcarousel/
and
http://www.gmarwaha.com/jquery/jcarousellite/
