### ISSUE TITLE
Cachedcommons.org has gone down

### ISSUE THREAD

**Issue by FellowshipAgency** [lancejpollard/cached-commons#74]
The site is down, any site relying on this service has a problem.

**Comment by adamjohnson** [comment]
Confirmed. What's goin' on?

**Comment by FellowshipAgency** [comment]
It's back up now, but not before I changed all of my sites to stop using it.

This project seems to be abandoned anyway, with scripts not updated for 2 years.

**Comment by thomasdavis** [comment]
Anyone looking for alternative -> http://cdnjs.com
