### ISSUE TITLE
jCarousel Request

### ISSUE THREAD

**Issue by jeffdeville** [lancejpollard/cached-commons#8]
Please add jcarousel: http://sorgalla.com/projects/jcarousel/
already hosted on github here: http://github.com/jsor/jcarousel

**Comment by lancejpollard** [comment]
Added!

http://cachedcommons.org/cache/jquery-jcarousel/0.2.5/javascripts/jquery-jcarousel.js

**Comment by jeffdeville** [comment]
Thanks Lance!
