### ISSUE TITLE
Date.js

### ISSUE THREAD

**Issue by eyeseast** [lancejpollard/cached-commons#9]
Please add date.js. It's a brain saver.

Homepage: http://www.datejs.com/
Repo (Google Code): http://code.google.com/p/datejs/

Much appreciated.

**Comment by lancejpollard** [comment]
Added!  You can find the specific translations by checking the paths in the source, until I figure out a good way to show multiple versions :).  Coming soon!

http://cachedcommons.org/cache/datejs/1.0.0/javascripts/date.js
